version: "3.5"
networks:
  broker:
    name: broker


services:
  # traefic template from https://gist.github.com/Mau5Machine/00401feb19433cf0387cc66c8e90c26c
  #
  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4

    ports:
      # Enables the web UI and tells Traefik to listen to docker
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
      # regular web
      - "80:80"
      - "443:443"

    # explicit stops should be honered, everything else is concidered accidental
    restart: unless-stopped

    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

      # Volume for certs (TLS)
      - type: bind
        source: ./letsencrypt
        target: /letsencrypt

      # storing log file
      - type: bind
        source: ./logs
        target: /logs

      # static config file
      - type: bind
        source: ./traefik.yml
        target: /etc/traefik/traefik.yml

      # server certificates
      - type: bind
        source: ./server
        target: /server

    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      ### see https://doc.traefik.io/traefik/v2.0/routing/routers/ for more
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.api.rule=HostRegexp(`traefik.{anydomain:.*}`,`proxy.{anydomain:.*}`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access

      # allow CORS:
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST"
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginListRegex=(.*)"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=content-type,hx-request,hx-current-url,hx-prompt,hx-history-restore-request,hx-target,hx-trigger-name,hx-trigger" # zie https://htmx.org/reference/#request_headers
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.cors.headers.accessControlExposeHeaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

      # www to non-www
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https?://www.(.+)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"

      # define only: strip front-end version: (/v0.9/front_end/ -> /front_end/)
      - "traefik.http.middlewares.strip-front-end-version.stripprefixregex.regex=^/(dev|v?[0-9.]+)/"

    networks:
      broker:
        aliases:
          - proxy
