# Go Templating only works along with dedicated dynamic configuration files.
# Templating does not work in the Traefik main static configuration file.
# :'(
# Own solution: use `invoke setup` to apply templates.
# indention is preserved, {ENV_VAR} is substituted,


api:
  insecure: false
  dashboard: false
  debug: false

accessLog:
  filePath: /logs/traefik-access.log
  fields:
    defaultMode: keep
    headers:
      names:
        User-Agent: keep
        Authorization: drop
        Cookie: drop
        Accept-Language: keep

log:
  ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
  level: DEBUG


providers:
  file:
    filename: /server/dynamic.yaml
    watch: true
  docker:
    # main help: https://doc.traefik.io/traefik/providers/docker/
    exposedByDefault: false
    network: broker

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secured
          scheme: https
          permanent: true
  web-secured:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: remco@isdruk.nl # template: email: {TRAEFIK_CERTIFICATE_EMAIL}
      storage: /letsencrypt/letsencrypt.json
      httpChallenge:
        entryPoint: web
  staging:
    acme:
      email: remco@isdruk.nl # template: email: {TRAEFIK_CERTIFICATE_EMAIL}
      storage: /letsencrypt/staging.json
      httpChallenge:
        entryPoint: web

tls: # https://doc.traefik.io/traefik/https/tls/#minimum-tls-version & https://www.djpic.net/articles/traefik-v2-secure-tls-and-header-configuration-with-docker-provider/
  options:
    edwh-std-tls-options:
      minVersion: VersionTLS12
      cipherSuites:
       # Recommended ciphers for TLSv1.2
       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       # Recommended ciphers for TLSv1.3
       - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    tlsv13only:
      minVersion: VersionTLS13



http:
  middlewares:
    superset-cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowMethods:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true

  routers:
    my-router:
      rule: "Host(`superset.utils2.edwh.nl`)"
      middlewares:
        - superset-cors
    # Bijbehorende labesl voor je docker compose service en CORS headers:
    #  - "traefik.http.routers.my-router.middlewares=superset-cors"
    #  - "traefik.http.middlewares.superset-cors.headers.accesscontrolalloworiginlist=*"
    #  - "traefik.http.middlewares.superset-cors.headers.accesscontrolallowmethods=*"
    #  - "traefik.http.middlewares.superset-cors.headers.accesscontrolallowheaders=*"
