server {
    listen 80;
    server_name _;

    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        return 404;
    }

    error_page 404 /404.html;
}
